# Generated by Django 5.2.1 on 2025-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Krishok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('nid', models.CharField(max_length=20, unique=True)),
                ('birth_certificate', models.FileField(upload_to='birth_certificates/')),
            ],
        ),
    ]
