# Generated by Django 5.2.1 on 2025-05-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krishok_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('assistance_type', models.CharField(choices=[('loan', 'ঋণ সহায়তা'), ('subsidy', 'সাবসিডি'), ('equipment', 'কৃষিযন্ত্র সহায়তা'), ('training', 'প্রশিক্ষণ/শিক্ষা')], max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
